---
title: "Publications"
date: 2021-02-08T10:28:47+13:00
---

Falster, A. D., R. Gallagher, E. Wenk, I. Wright, D. Indiarto, S. C. Andrew, J. Lawson, S. Allen, A. Fuchs, M. A. Adams, W. Collin, M. Alfonzetti, T. Angevin, O. K. Atkin, T. Auld, A. Baker, G. Buckton, G. Burrows, E. Caldwell, J. Camac, R. Carpenter, A. Catford, G. R. Cawthray, L. A. Cernusak, G. Chandler, A. R. Chapman, A. W. Cheesman, S. Chen, B. Choat, B. Clinton, P. Clode, H. Coleman, W. K. Cornwell, M. Cosgrove, M. Crisp, E. Cross, Y. Crous, S. Cunningham, E. Curtis, M. I. Daws, J. L. Degabriel, D. Matthew, N. Dong, H. Duan, D. H. Duncan, R. P. Duncan, M. Duretto, J. M. Dwyer, C. Edwards, M. Esperon-rodriguez, J. R. Evans, S. E. Everingham, J. Firn, C. R. Fonseca, B. J. French, D. Frood, J. L. Funk, R. Sonya, O. Ghannoum, S. M. Gleason, C. R. Gosper, E. Gray, P. K. Groom, C. Gross, G. Guerin, L. Guja, A. K. Hahs, M. T. Harrison, E. Patrick, J. K. Mccarthy, T. Meers, M. Van Der Merwe, D. Metcalfe, and P. Milberg. 2021. AusTraits – a curated plant trait database for the Australian flora. bioRxiv:1–62.

Lai, H. R., G. S. Y. Tan, L. Neo, C. Y. Kee, A. T. K. Yee, H. T. W. Tan, and K. Y. Chong. 2020. Decoupled responses of native and exotic tree diversities to distance from old-growth forest and soil phosphorus in novel secondary forests. Applied Vegetation Science.

Song, X. P., H. R. Lai, L. S. Wijedasa, P. Y. Tan, P. J. Edwards, and D. R. Richards. 2020. Height–diameter allometry for the management of city trees in the tropics. Environmental Research Letters 15:114017.

Lai, H. R., K. Y. Chong, D. B. Stouffer, and M. M. Mayfield. 2020. The role of higher-order biotic interactions on tropical tree growth. bioRxiv.

Yee, A. T. K., H. R. Lai, K. Y. Chong, L. Neo, C. Y. Koh, S. Y. Tan, W. W. Seah, J. W. Loh, R. C. J. Lim, M. van Breugel, and H. T. W. Tan. 2019. Short-term responses in a secondary tropical forest after a severe windstorm event. Journal of Vegetation Science 30:720–731.

Lai, H. R., K. Y. Chong, A. T. K. Yee, H. T. W. Tan, and M. van Breugel. 2020. Functional traits that moderate tropical tree recruitment during post-windstorm secondary succession. Journal of Ecology 108:1322–1333.

Chiam, Z., X. P. Song, H. R. Lai, and H. T. W. Tan. 2019. Particulate matter mitigation via plants: Understanding complex relationships with leaf traits. Science of the Total Environment 688:398–408.

van Breugel, M., D. Craven, H. R. Lai, M. Baillon, B. L. Turner, and J. S. Hall. 2019. Soil nutrients and dispersal limitation shape compositional variation in secondary tropical forests across multiple scales. Journal of Ecology 107:566–581.

Lam, W. N., H. R. Lai, C. C. Lee, and H. T. W. Tan. 2018. Evidence for pitcher trait-mediated coexistence between sympatric Nepenthes pitcher plant species across geographical scales. Plant Ecology and Diversity 11:283–294.

Bimler, M. D., D. B. Stouffer, H. R. Lai, and M. M. Mayfield. 2018. Accurate predictions of coexistence in natural systems require the inclusion of facilitative interactions and environmental dependency. Journal of Ecology 106:1839–1852.

Wainwright, C. E., J. HilleRisLambers, H. R. Lai, X. Loy, and M. M. Mayfield. 2019. Distinct responses of niche and fitness differences to water availability underlie variable coexistence outcomes in semi-arid annual plant communities. Journal of Ecology 107:293–306.

Lai, H. R., J. S. Hall, S. A. Batterman, B. L. Turner, and M. van Breugel. 2018. Nitrogen fixer abundance has no effect on biomass recovery during tropical secondary forest succession. Journal of Ecology 106:1415–1427.

Sams, M. A., H. R. Lai, S. P. Bonser, P. A. Vesk, R. M. Kooyman, D. J. Metcalfe, J. W. Morgan, and M. M. Mayfield. 2017. Landscape context explains changes in the functional diversity of regenerating forests better than climate or species richness. Global Ecology and Biogeography 26:1165–1176.

Wainwright, C. E., T. L. Staples, L. S. Charles, T. C. Flanagan, H. R. Lai, X. Loy, V. A. Reynolds, and M. M. Mayfield. 2018. Links between community ecology theory and ecological restoration are on the rise. Journal of Applied Ecology 55:570–581.

Lai, H. R., J. S. Hall, B. L. Turner, and M. van Breugel. 2017. Liana effects on biomass dynamics strengthen during secondary forest succession. Ecology 98:1062–1070.

Lai, H. R., M. M. Mayfield, J. M. Gay-des-combes, T. Spiegelberger, and J. M. Dwyer. 2015. Distinct invasion strategies operating within a natural annual plant system. Ecology Letters 18:336–346.