---
title: "Projects"
---

# Projects & research interests

## [Trait-based species distribution modelling](#traitSDM)

- We can now model the environmental response or niche of multiple species simultaneously using joint species distribution models.
- But can we *generalise* interspecific differences in environmental niche using functional traits? 
- How *transferable* is a trait-based species distribution model across space, time, and taxa?
- Published work:
    - Trait-moderated sapling recruitment and mortality across a forest-successional gradient (*coming soon*)
    - [Trait-moderated tree recruitment across post-windstorm environmental gradients](https://doi.org/10.1111/1365-2745.13347)

## [Higher-order biotic interactions](#hoi)

- Species *pairs* are often the study unit of biotic interactions.
- In multispecies assemblages, however, "intermediary species" outside the focal pair can interfere with the direct pairwise interaction.
- Regardless of the biological mechanism, these interferences can manifest as non-negligible higher-order statistical terms that, when ignored, can result in inaccurate predictions of community dynamics.
- Under what conditions do we expect higher-order interactions to be strong? Where do we expect higher-order interactions to be prevalent?
- Including higher-order statistical terms introduces *a lot of* extra parameters. How do we deal with such model complexities?
- Published work:
    - [Non-additive biotic interactions and tropical tree growth](https://doi.org/10.1101/2020.09.16.300616)

## [Predicting tree growth and dimensions](#trees)

- What trees do best under the sun is grow. Heck, they even do it under deep shade.
- Because we are not trees, however, we need to understand the abiotic and biotic factors of tree growth, as well as how different physical dimensions (e.g., height, diameter, biomass, crown) scale with one another.
- Published work:
    - [Height–diameter allometry in the Singapore urbanscape](https://doi.org/10.1088/1748-9326/abbbad)
    - [Non-additive biotic interactions and tropical tree growth](https://doi.org/10.1101/2020.09.16.300616)
    - [Effects of woody climbers on stand-level tree growth](http://doi.wiley.com/10.1002/ecy.1734)
    - [Effects of nitrogen fixers on stand-level tree growth](https://doi.org/10.1111/1365-2745.12979)
    
## [Functional trait databases](#trait-data)

- For ecology to progress we need to share data. 
- Very much work(s) in progress.
- Published work:
    - [AusTraits for Australian flora](https://doi.org/10.1101/2021.01.04.425314)
    - [Traits for some Singaporean secondary-forest trees](https://doi.org/10.1111/1365-2745.13347)