---
title: "Open data"
date: 2021-02-09
bibliography: bib.bib
csl: journal-of-ecology.csl
---

```{css, echo=FALSE}
.csl-entry {
  padding-left: 36px ;
  text-indent: -36px ;
}
```

# Open science + data

Feel free to play around with the data or models. Issues or questions can be discussed on each of the GitHub Issue pages.

## @Lai2024: tree competition and diameter growth along broad environmental gradients

- Download from [GitHub/Zenodo](https://zenodo.org/records/10815402)
- Our paper in [*The American Naturalist*](https://doi.org/10.1086/730807)

## @Lai2021: tree competition and diameter growth

- Download from [GitHub/Zenodo](https://zenodo.org/records/5430441)
- Our paper in [*Ecology*](https://doi.org/10.1002/ecy.3588)

## @Falster2021: `AusTraits` --- a curated plant trait database for the Australian flora

- `R` package [here](https://austraits.org/)
- Our paper in [*Nature Scientific Data*](https://www.nature.com/articles/s41597-021-01006-6)

## @Lai2021b: trait--environment dependent sapling demography using `boral`

- Download from [GitHub](https://github.com/hrlai/Lai_et_al_2021_EcolLett_Trait_Age) or [Zenodo](https://doi.org/10.5281/zenodo.5183031)
- Our paper in [*Ecology Letters*]( https://doi.org/10.1111/ele.13784)

## @Lai2021a: `novelforestSG`---diversity, abiotic factors and `brms` model

- Install from [CRAN](https://cran.r-project.org/web/packages/novelforestSG/index.html)
- Detailed instructions on [GitHub](https://github.com/hrlai/novelforestSG) or [GitHub Pages](https://hrlai.github.io/novelforestSG/)
- Our paper in [*Applied Vegetation Science*](https://doi/10.1111/avsc.12548)

## @Lai2020: fourth-corner joint species distribution model using `boral`

- Download from [GitHub](https://github.com/hrlai/Lai_et_al_2020_JEcol_Trait_Env)
- Our paper in [*Journal of Ecology*](https://doi.org/10.1111/1365-2745.13347)

## @Song2020: `allometree`---an `R` package for urban tree size allometry

- Download from [GitHub](https://github.com/xp-song/allometree)
- Our paper in [*Environmental Research Letters*](https://doi.org/10.1088/1748-9326/abbbad)

# References
